#!/usr/bin/env python3
"""Compile source-verified elementary achievement standards into Markdown wiki pages.

The input directory must contain XML generated by `hwp5proc xml --format nested`:

- doc-06.xml: 2022 Korean curriculum appendix 5
- doc-09.xml: 2022 mathematics curriculum appendix 8
- doc-11.xml: 2022 integrated curriculum appendix 15
- achievement-34.xml: official 3-4 grade-band achievement-level document
- achievement-56.xml: official 5-6 grade-band achievement-level document

This maintenance tool stores only achievement-standard text and routing metadata. It
does not ingest textbook prose, activities, or exercises.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path
from xml.etree import ElementTree as ET


SKILL_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_WIKI_ROOT = SKILL_ROOT / "references" / "curriculum-wiki"


@dataclass(frozen=True)
class PageSpec:
    subject: str
    slug: str
    grade_band: str
    code_prefix: str
    source_file: str
    source_id: str
    expected_count: int


SPECS = (
    PageSpec("국어", "korean", "1-2", "국", "doc-06.xml", "moe-2022-korean-curriculum", 23),
    PageSpec("국어", "korean", "3-4", "국", "achievement-34.xml", "ncic-2024-achievement-levels-3-4", 30),
    PageSpec("국어", "korean", "5-6", "국", "achievement-56.xml", "ncic-2024-achievement-levels-5-6", 34),
    PageSpec("수학", "math", "1-2", "수", "doc-09.xml", "moe-2022-math-curriculum", 29),
    PageSpec("수학", "math", "3-4", "수", "achievement-34.xml", "ncic-2024-achievement-levels-3-4", 47),
    PageSpec("수학", "math", "5-6", "수", "achievement-56.xml", "ncic-2024-achievement-levels-5-6", 45),
    PageSpec("도덕", "moral", "3-4", "도", "achievement-34.xml", "ncic-2024-achievement-levels-3-4", 12),
    PageSpec("도덕", "moral", "5-6", "도", "achievement-56.xml", "ncic-2024-achievement-levels-5-6", 12),
    PageSpec("사회", "social", "3-4", "사", "achievement-34.xml", "ncic-2024-achievement-levels-3-4", 22),
    PageSpec("사회", "social", "5-6", "사", "achievement-56.xml", "ncic-2024-achievement-levels-5-6", 27),
    PageSpec("과학", "science", "3-4", "과", "achievement-34.xml", "ncic-2024-achievement-levels-3-4", 51),
    PageSpec("과학", "science", "5-6", "과", "achievement-56.xml", "ncic-2024-achievement-levels-5-6", 51),
    PageSpec("실과", "practical-arts", "5-6", "실", "achievement-56.xml", "ncic-2024-achievement-levels-5-6", 39),
    PageSpec("체육", "physical-education", "3-4", "체", "achievement-34.xml", "ncic-2024-achievement-levels-3-4", 23),
    PageSpec("체육", "physical-education", "5-6", "체", "achievement-56.xml", "ncic-2024-achievement-levels-5-6", 26),
    PageSpec("음악", "music", "3-4", "음", "achievement-34.xml", "ncic-2024-achievement-levels-3-4", 13),
    PageSpec("음악", "music", "5-6", "음", "achievement-56.xml", "ncic-2024-achievement-levels-5-6", 13),
    PageSpec("미술", "art", "3-4", "미", "achievement-34.xml", "ncic-2024-achievement-levels-3-4", 13),
    PageSpec("미술", "art", "5-6", "미", "achievement-56.xml", "ncic-2024-achievement-levels-5-6", 13),
    PageSpec("영어", "english", "3-4", "영", "achievement-34.xml", "ncic-2024-achievement-levels-3-4", 20),
    PageSpec("영어", "english", "5-6", "영", "achievement-56.xml", "ncic-2024-achievement-levels-5-6", 20),
    PageSpec("바른 생활", "integrated/ethical-life", "1-2", "바", "doc-11.xml", "moe-2022-integrated-curriculum", 16),
    PageSpec("슬기로운 생활", "integrated/intelligent-life", "1-2", "슬", "doc-11.xml", "moe-2022-integrated-curriculum", 16),
    PageSpec("즐거운 생활", "integrated/pleasant-life", "1-2", "즐", "doc-11.xml", "moe-2022-integrated-curriculum", 16),
)


SUBJECT_NOTES = {
    "국어": "문항의 담화·글·작품·매체 자료는 저작권이 확인된 사용자 자료나 새로 쓴 짧은 자료를 사용한다.",
    "수학": "학년군 성취기준은 학기 배치를 확정하지 않는다. 나선형 위계와 학기별 범위는 검토된 단원 오버라이드가 있을 때만 강제한다.",
    "도덕": "가치 판단 문항은 하나의 삶의 태도를 단순 암기 정답으로 만들지 않고 성취기준의 판단 근거를 묻는다.",
    "사회": "시사 사실을 사용할 때는 최신성과 출처를 별도로 확인하고, 학년군 범위보다 전문적인 법·경제 용어를 피한다.",
    "과학": "관찰·분류·예상·추리 등 탐구 기능을 포함하되 중학교의 형식적 공식이나 입자 수준 설명을 앞당기지 않는다.",
    "실과": "안전·개인정보·디지털 윤리 관련 문항은 현재 지침과 학교 맥락을 함께 확인한다.",
    "체육": "신체 수행을 지필 지식만으로 대체하지 않는다. 퀴즈는 개념·안전·전략·성찰을 보조 평가한다.",
    "음악": "듣기 자료가 없으면 실제 청음 여부를 가장하는 문항을 만들지 않는다.",
    "미술": "작품 이미지를 쓰는 경우 저작권과 시각 정보의 충분성을 확인한다.",
    "영어": "어휘·문장 복잡도와 의사소통 기능을 학년군 수준에 맞추며 번역 지식만 묻는 문항 편중을 피한다.",
    "바른 생활": "실천 경험 중심 교과이므로 퀴즈는 생활 성찰과 안전한 판단을 보조하며 행동 실천 자체를 대체하지 않는다.",
    "슬기로운 생활": "학생의 실제 생활과 주변 탐구를 바탕으로 하며, 3학년 이후 분과 지식을 앞당기지 않는다.",
    "즐거운 생활": "놀이·표현·감상 경험을 보조하되 활동 수행을 객관식 지식 문항으로 대체하지 않는다.",
}

STATEMENT_CORRECTIONS = {
    "[6수01-10]": "‘(자연수)÷(자연수)’에서 나눗셈의 몫을 분수로 나타낼 수 있다.",
    "[6수01-14]": "‘(자연수)÷(자연수)’에서 나눗셈의 몫을 소수로 나타낼 수 있다.",
}


def xml_paragraphs(path: Path) -> list[str]:
    root = ET.parse(path).getroot()
    return [
        re.sub(r"\s+", " ", "".join((node.text or "") for node in paragraph.iter("Text"))).strip()
        for paragraph in root.iter("Paragraph")
    ]


def clean_statement(raw: str) -> str:
    achievement_levels = re.search(
        r"A\s*(?=[가-힣‘(0-9]).*B\s*(?=[가-힣‘(0-9]).*C\s*(?=[가-힣‘(0-9])",
        raw,
    )
    if achievement_levels:
        raw = raw[: achievement_levels.start()]
    raw = re.split(r"탐구\s*활동|※|[\ue000-\uf8ff\U000F0000-\U000FFFFD]|(?<=\.)\s+\(\d+\)\s+[가-힣]", raw, maxsplit=1)[0]
    raw = re.sub(r"^[\s:·•]+|[\s:·•]+$", "", raw)
    raw = re.sub(r"\s+", " ", raw).strip()
    if raw.endswith("다"):
        raw += "."
    return raw


def extract_standards(paragraphs: list[str], grade: str, prefix: str) -> list[dict[str, str]]:
    code_pattern = re.compile(rf"\[{re.escape(grade + prefix)}\d{{2}}-\d{{2}}\]")
    any_code_pattern = re.compile(r"\[[1-9][가-힣]+\d{2}-\d{2}\]")
    standards: dict[str, str] = {}
    for paragraph in paragraphs:
        matches = list(any_code_pattern.finditer(paragraph))
        for index, match in enumerate(matches):
            code = match.group(0)
            if not code_pattern.fullmatch(code) or code in standards:
                continue
            end = matches[index + 1].start() if index + 1 < len(matches) else len(paragraph)
            statement = clean_statement(paragraph[match.end() : end])
            if len(statement) >= 8:
                standards[code] = statement
    return [
        {"code": code, "statement": STATEMENT_CORRECTIONS.get(code, standards[code])}
        for code in sorted(standards)
    ]


def source_hash(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def json_block(data: dict) -> str:
    return json.dumps(data, ensure_ascii=False, indent=2)


def render_page(spec: PageSpec, standards: list[dict[str, str]], xml_hash: str) -> str:
    grade = spec.grade_band[-1]
    areas: dict[str, list[dict[str, str]]] = {}
    for standard in standards:
        area = re.search(rf"\[{grade}{re.escape(spec.code_prefix)}(\d{{2}})-", standard["code"]).group(1)
        areas.setdefault(area, []).append(standard)
    rules = {
        "curriculum": "2022 개정 교육과정",
        "subject": spec.subject,
        "grade_band": spec.grade_band,
        "standards": standards,
        "scope_guardrails": [
            SUBJECT_NOTES[spec.subject],
            "이 문서는 학년군 범위를 제시하며 개별 학기나 교과서 단원 순서를 확정하지 않는다.",
        ],
        "sources": [spec.source_id],
        "source_xml_sha256": xml_hash,
    }
    lines = [
        "---",
        f"id: {spec.slug.replace('/', '-')}-grade-{spec.grade_band}",
        "page_type: grade_band",
        "status: source_verified",
        "verified_at: 2026-06-27",
        "---",
        "",
        f"# {spec.subject} {spec.grade_band}학년군",
        "",
        "공식 교육과정·성취수준 문서에서 성취기준 코드와 문장을 추출해 원문과 대조 가능한 형태로 저장한 범위 페이지다.",
        "",
        "```json curriculum-rules",
        json_block(rules),
        "```",
        "",
        "## 성취기준 빠른 보기",
        "",
    ]
    for area, values in sorted(areas.items()):
        lines.extend([f"### 영역 {area}", ""])
        lines.extend(f"- {item['code']} {item['statement']}" for item in values)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_subject_index(subject: str, slug: str, specs: list[PageSpec]) -> str:
    links = "\n".join(
        f"- [{spec.grade_band}학년군](grade-bands/{spec.grade_band}.md)" for spec in sorted(specs, key=lambda item: item.grade_band)
    )
    return (
        "---\n"
        f"id: {slug.replace('/', '-')}-index\n"
        "page_type: subject_index\n"
        "status: reviewed\n"
        "verified_at: 2026-06-27\n"
        "---\n\n"
        f"# {subject}\n\n"
        f"{links}\n"
    )


def compile_pages(source_dir: Path, wiki_root: Path) -> dict:
    paragraph_cache: dict[str, list[str]] = {}
    hash_cache: dict[str, str] = {}
    written = []
    grouped: dict[tuple[str, str], list[PageSpec]] = {}
    counts = {}

    for spec in SPECS:
        source_path = source_dir / spec.source_file
        if not source_path.is_file():
            raise SystemExit(f"Missing source XML: {source_path}")
        paragraphs = paragraph_cache.setdefault(spec.source_file, xml_paragraphs(source_path))
        xml_hash = hash_cache.setdefault(spec.source_file, source_hash(source_path))
        standards = extract_standards(paragraphs, spec.grade_band[-1], spec.code_prefix)
        if len(standards) != spec.expected_count:
            raise SystemExit(
                f"{spec.subject} {spec.grade_band}: expected {spec.expected_count} standards, extracted {len(standards)}"
            )
        output = wiki_root / spec.slug / "grade-bands" / f"{spec.grade_band}.md"
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(render_page(spec, standards, xml_hash), encoding="utf-8")
        written.append(output)
        counts[f"{spec.subject}:{spec.grade_band}"] = len(standards)
        grouped.setdefault((spec.subject, spec.slug), []).append(spec)

    for (subject, slug), specs in grouped.items():
        index = wiki_root / slug / "index.md"
        if subject == "수학" and index.exists():
            continue
        index.parent.mkdir(parents=True, exist_ok=True)
        index.write_text(render_subject_index(subject, slug, specs), encoding="utf-8")
        written.append(index)

    return {"pages_written": len(written), "standard_counts": counts}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", type=Path, required=True)
    parser.add_argument("--wiki-root", type=Path, default=DEFAULT_WIKI_ROOT)
    args = parser.parse_args()
    result = compile_pages(args.source_dir, args.wiki_root)
    print(json.dumps({"status": "pass", **result}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
